### ISSUE TITLE
Change the verbose name of the action

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/actions#11]
Multiple times now, I've surprised myself and tried to click the check for the PR docs links action in the PR list of checks. Apparently I'm confused by how prominent the check looks, but of course the "details" link for that check does not do what you expect.

I'm actually not even sure where this name comes from, but just assuming its centrally configured here somehow.

So, I would say this first check is more prominent that our own RTD build check:

![sorry, github is broken](https://usercontent.irccloud-cdn.com/file/sXxzIuWH/image.png)

And even though our check has our icon in that list, I still somehow want to click the first check, the check for the links. So, if I am actively/subconsciously doing this as someone familiar with RTD, there must be others that would notice this.

Looking more at this, "Read the Docs" looks more official than "docs/readthedocs.com:...", and the first link mentions "pull request preview". Though the links are in the PR description, users are probably still used to clicking the check detail links, so would be bound to hit this confusion.

This is a case where showing this action in the PR action list is probably a worse scenario, but that's up to GitHub to deal with.

But because we shouldn't expect users to interact with this particular action in the list of checks, I think a much less prominent name would at least not overwhelm our actual PR check.

We could follow the naming scheme used in other checks, this is definitely less prominent and doesn't make me want to keep clicking it.

![great job github](https://usercontent.irccloud-cdn.com/file/eaN6kWOd/image.png)

**Comment by humitos** [comment]
> I'm actually not even sure where this name comes from, but just assuming its centrally configured here somehow.

The names comes from https://github.com/readthedocs/actions/blob/main/.github/workflows/readthedocs-preview.yaml#L1

It's a combination of:

- the name of the action
- the filename
- the event registered

So, we can update our example to make it simpler --but it's per-repository, so it won't change the name from repositories already using the action.

**Comment by humitos** [comment]
I tweaked it a little following your suggestion and ended up with the following:

![Screenshot_2022-08-18_10-45-23](https://user-images.githubusercontent.com/244656/185352375-e67ce1f2-f805-445e-8575-4fbb68ee7351.png)

If you are happy with it, we should change the documentation at https://github.com/readthedocs/actions/tree/main/preview#how-to-use-it as well. Let me know!

**Comment by agjohnson** [comment]
Ah yeah, looks much better! I don't think I'd click on that first

**Comment by humitos** [comment]
Cool! Closed by https://github.com/readthedocs/actions/commit/f132761555725a8a8ed40ff29d7de22522b096b4
