### ISSUE TITLE
Publish this action in the Marketplace

### ISSUE THREAD

**Issue by humitos** [readthedocs/actions#18]
After merging #16 and releasing a new `v1` in #17; it would be good to publish this action in the GitHub Marketplace so people can find it easily. I don't have experience about how it works, but it would be good to research a little.

https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

**Comment by humitos** [comment]
Meh, we decided to store multiple actions in _one repository_ some time ago. Due to that, we cannot public the action in the marketplace: 

> Each repository must contain a single action.
> The action's metadata file (action.yml or action.yaml) must be in the root directory of the repository.

I don't think it's worth to roll back this decision now. Publishing in the marketplace is a nice to have, and I don't think we will get lot of benefits from it, considering the work we have to undo now.

**Comment by ericholscher** [comment]
@humitos Annoying limitation, but I'm fine with that 👍
