### ISSUE TITLE
`books` emoji doesn't seem to render when added by the bot

### ISSUE THREAD

**Issue by egeakman** [readthedocs/actions#34]
I've noticed the issue at python/docs-community#92, but it seems that other repos are affected as well.

When you type in `:books:` manually, it gets rendered:
![image](https://github.com/readthedocs/actions/assets/75242929/0b5f2789-27d3-4416-8588-937560b8c0a2)

Adding a space in the first emoji fixes the second emoji:
![image](https://github.com/readthedocs/actions/assets/75242929/ac30d62e-9c6d-4306-b414-927ecf25d46d)

Using the emoji (📚) directly rather than using its name (`:books:`) might fix it!

Also, should these be concerning?
![image](https://github.com/readthedocs/actions/assets/75242929/e20b5f1d-bfbb-409c-b0f4-4fcc7a9f998c)

**Comment by humitos** [comment]
Hi! Thanks for the report. @egeakman @pjonsson Would you mind overwriting `message-template` variable in your YAML file with the text that makes the emoji to render correctly?

**Comment by pjonsson** [comment]
> Hi! Thanks for the report. @egeakman @pjonsson Would you mind overwriting `message-template` variable in your YAML file with the text that makes the emoji to render correctly?

https://github.com/pjonsson/datacube-explorer/pull/3/files shows what I merged, and then I made  https://github.com/pjonsson/datacube-explorer/pull/4 after that was merged.

Attaching a screenshot of the result, the first books emoji is written with colons, the second/third books use the symbol directly.
![image](https://github.com/readthedocs/actions/assets/2082449/667ac5a7-d137-495f-9592-7edb61ae03ee)
