### ISSUE TITLE
Read the Docs Actions maintenance

### ISSUE THREAD

**Issue by Jamim** [readthedocs/actions#36]
Hello @humitos,

First of all, thank you for your work on actions 🙇🏻‍♂️

Sadly, now this repository [looks abandoned](https://github.com/readthedocs/actions/branches).
I believe the community still need this repository to be maintained.
For instance, [python/peps](https://github.com/python/peps) suffers from #34 while there is already a trivial fix #32.

I understand that you probably might have no time to deal with it right now, but would you mind considering delegating maintenance to some member of [Read the Docs](https://github.com/readthedocs)?

Thanks in advance!

**Comment by humitos** [comment]
Hi @Jamim! Thanks for opening this issue.

This project is not abandoned and it's maintained, yes.

> For instance, [python/peps](https://github.com/python/peps) suffers from #34 while there is already a trivial fix #32.

The PR that you mentioned was opened 9 days ago. If you are hitting this issue and want a quick workaround, you can overwrite the `meesage-template`  variable in your YAML file.

> I understand that you probably might have no time to deal with it right now, but would you mind considering delegating maintenance to some member of [Read the Docs](https://github.com/readthedocs)?

This repository is already under the Read the Docs organization on GitHub.
