### ISSUE TITLE
Any approach to disable the preview build for certain pull requests?

### ISSUE THREAD

**Issue by huxuan** [readthedocs/actions#39]
Seems what the "[readthedocs/actions/preview](https://github.com/readthedocs/actions/tree/v1/preview)" action do is adding preview links to the pull request description. With certain "paths" configuration according to the [documentation](https://github.com/readthedocs/actions/blob/v1/preview/README.md), even though the preview links will not be added, but it seems that the buld process is still triggerred. Any approach to disable the build process (to save resources)?

**Comment by humitos** [comment]
Hi, the GitHub action is not related with the build process itself. So, it cannot be skipped using this action.

However, you can take a look at https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition to skip the build itself on Read the Docs by defining a custom command.

Let me know if that helps.

**Comment by huxuan** [comment]
> However, you can take a look at https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition to skip the build itself on Read the Docs by defining a custom command.

Wow, that looks cool! I will further investigate on it.

Thanks for your help!

Close this isuue then.
